from __future__ import annotations

from typing import Protocol

from tlvflow.domain.maintenance_event import MaintenanceEvent
from tlvflow.domain.payment import Payment
from tlvflow.domain.rides import Ride
from tlvflow.domain.users import User
from tlvflow.domain.vehicles import Vehicle


class UsersRepositoryProtocol(Protocol):
    def get_by_id(self, user_id: str) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def add(self, user: User) -> None: ...


class ActiveUsersRepositoryProtocol(Protocol):
    def get_ride_id(self, user_id: str) -> str | None: ...

    def is_active(self, user_id: str) -> bool: ...

    def set_active(self, user_id: str, ride_id: str) -> None: ...

    def clear(self, user_id: str) -> None: ...

    def get_active_user_ids(self) -> list[str]: ...


class RidesRepositoryProtocol(Protocol):
    def get_by_id(self, ride_id: str) -> Ride | None: ...

    def get_by_user_id(self, user_id: str) -> list[Ride]: ...

    def add(self, ride: Ride) -> None: ...


class MaintenanceRepositoryProtocol(Protocol):
    def add(self, event: MaintenanceEvent) -> None: ...

    def get_by_id(self, event_id: str) -> MaintenanceEvent | None: ...

    def get_all(self) -> list[MaintenanceEvent]: ...

    def get_by_vehicle_id(self, vehicle_id: str) -> list[MaintenanceEvent]: ...


class DegradedVehiclesRepositoryProtocol(Protocol):
    def add(self, vehicle: Vehicle) -> None: ...

    def remove(self, vehicle_id: str) -> Vehicle | None: ...

    def get_all(self) -> list[Vehicle]: ...

    def get_by_id(self, vehicle_id: str) -> Vehicle | None: ...

    def clear(self) -> None: ...


class PaymentsRepositoryProtocol(Protocol):
    def get_by_id(self, payment_id: str) -> Payment | None: ...

    def get_by_ride_id(self, ride_id: str) -> list[Payment]: ...

    def add(self, payment: Payment) -> None: ...
